version: "3"

services:
  backend:
    image: quarkus/api-comparison-jvm
    build:
      context: backend
      dockerfile: src/main/docker/Dockerfile.jvm
    ports:
      - "8080:8080"

  proxy:
    image: envoy
    build:
      context: proxy
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
